; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.1.3-LPC on Mon Aug 03 2020 18:49:08 GMT+0200 (Mitteleuropäische Sommerzeit)
M581 S-1 T2 ; neutralise trigger 2  while stopping print
G1 X{move.axes[0].min} Y{move.axes[1].max} F6000
M104 S-273
M140 S-273
G92 E0
M84
M106 S255
M109 R50
M81